// Sample data for portfolio - used when MongoDB is not connected

export const sampleAbout = {
  _id: '1',
  title: 'Full-Stack Web Developer',
  subtitle: 'Building Scalable MERN Applications',
  description: `I'm a passionate Full-Stack Web Developer with 5+ years of experience building web applications. 
I specialize in the MERN stack and love creating intuitive, performant applications that solve real-world problems.

When I'm not coding, you can find me exploring new technologies, contributing to open source, or sharing knowledge through technical writing.`,
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
  resume: '/resume.pdf',
  socialLinks: {
    github: 'https://github.com/alexjohnson',
    linkedin: 'https://linkedin.com/in/alexjohnson',
    twitter: 'https://twitter.com/alexjohnson',
    email: 'hello@alexjohnson.dev',
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
}

export const sampleSkills = [
  { _id: '1', name: 'React', category: 'Frontend', proficiency: 95, icon: 'react', createdAt: '', updatedAt: '' },
  { _id: '2', name: 'Next.js', category: 'Frontend', proficiency: 90, icon: 'nextjs', createdAt: '', updatedAt: '' },
  { _id: '3', name: 'TypeScript', category: 'Frontend', proficiency: 88, icon: 'typescript', createdAt: '', updatedAt: '' },
  { _id: '4', name: 'TailwindCSS', category: 'Frontend', proficiency: 95, icon: 'tailwind', createdAt: '', updatedAt: '' },
  { _id: '5', name: 'Node.js', category: 'Backend', proficiency: 92, icon: 'nodejs', createdAt: '', updatedAt: '' },
  { _id: '6', name: 'Express.js', category: 'Backend', proficiency: 90, icon: 'express', createdAt: '', updatedAt: '' },
  { _id: '7', name: 'MongoDB', category: 'Backend', proficiency: 85, icon: 'mongodb', createdAt: '', updatedAt: '' },
  { _id: '8', name: 'PostgreSQL', category: 'Database', proficiency: 80, icon: 'postgresql', createdAt: '', updatedAt: '' },
  { _id: '9', name: 'Git', category: 'Tools', proficiency: 90, icon: 'git', createdAt: '', updatedAt: '' },
  { _id: '10', name: 'Docker', category: 'Tools', proficiency: 75, icon: 'docker', createdAt: '', updatedAt: '' },
  { _id: '11', name: 'AWS', category: 'Tools', proficiency: 70, icon: 'aws', createdAt: '', updatedAt: '' },
  { _id: '12', name: 'Figma', category: 'Tools', proficiency: 80, icon: 'figma', createdAt: '', updatedAt: '' },
]

export const sampleProjects = [
  {
    _id: '1',
    title: 'E-Commerce Platform',
    slug: 'e-commerce-platform',
    description: 'A full-featured e-commerce platform with product management, cart functionality, payment processing via Stripe, and order tracking. Built with modern tech stack for optimal performance.',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop',
    images: [],
    techStack: ['Next.js', 'Node.js', 'MongoDB', 'Stripe', 'Tailwind'],
    githubUrl: 'https://github.com/example/ecommerce',
    liveUrl: 'https://example-ecommerce.com',
    category: 'Full-Stack',
    featured: true,
    createdAt: '2024-01-15',
    updatedAt: '',
  },
  {
    _id: '2',
    title: 'Task Management App',
    slug: 'task-management-app',
    description: 'A collaborative task management application with real-time updates, team workspaces, and Kanban boards. Features drag-and-drop functionality and team collaboration tools.',
    thumbnail: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&h=600&fit=crop',
    images: [],
    techStack: ['React', 'Express', 'Socket.io', 'PostgreSQL'],
    githubUrl: 'https://github.com/example/taskmanager',
    liveUrl: 'https://example-tasks.com',
    category: 'Full-Stack',
    featured: true,
    createdAt: '2024-02-20',
    updatedAt: '',
  },
  {
    _id: '3',
    title: 'AI Chat Assistant',
    slug: 'ai-chat-assistant',
    description: 'An intelligent chat assistant powered by OpenAI GPT-4, featuring context-aware conversations, custom training capabilities, and seamless integration with business workflows.',
    thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=600&fit=crop',
    images: [],
    techStack: ['Next.js', 'OpenAI', 'Vercel AI SDK', 'Tailwind'],
    githubUrl: 'https://github.com/example/ai-chat',
    liveUrl: 'https://example-ai.com',
    category: 'AI/ML',
    featured: true,
    createdAt: '2024-03-10',
    updatedAt: '',
  },
  {
    _id: '4',
    title: 'Real Estate Platform',
    slug: 'real-estate-platform',
    description: 'A modern real estate platform with property listings, virtual tours, interactive maps, and agent management system. Includes advanced filtering and search capabilities.',
    thumbnail: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop',
    images: [],
    techStack: ['React', 'Node.js', 'MongoDB', 'Mapbox'],
    githubUrl: 'https://github.com/example/realestate',
    category: 'Full-Stack',
    featured: false,
    createdAt: '2023-11-05',
    updatedAt: '',
  },
  {
    _id: '5',
    title: 'Fitness Tracker',
    slug: 'fitness-tracker',
    description: 'A comprehensive fitness tracking app with workout plans, progress charts, nutrition logging, and social features for community engagement and motivation.',
    thumbnail: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&h=600&fit=crop',
    images: [],
    techStack: ['React Native', 'Firebase', 'Redux'],
    githubUrl: 'https://github.com/example/fitness',
    liveUrl: 'https://example-fitness.com',
    category: 'Mobile',
    featured: false,
    createdAt: '2023-09-15',
    updatedAt: '',
  },
  {
    _id: '6',
    title: 'Portfolio Generator',
    slug: 'portfolio-generator',
    description: 'A drag-and-drop portfolio builder that allows developers to create stunning portfolios in minutes. Features customizable templates and easy deployment options.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop',
    images: [],
    techStack: ['Next.js', 'Prisma', 'PostgreSQL', 'Tailwind'],
    githubUrl: 'https://github.com/example/portfolio-gen',
    liveUrl: 'https://example-portfolio.com',
    category: 'SaaS',
    featured: false,
    createdAt: '2023-07-20',
    updatedAt: '',
  },
]

export const sampleExperience = [
  {
    _id: '1',
    company: 'Tech Startup Inc.',
    role: 'Senior Full-Stack Web Developer',
    description: 'Led the development of a SaaS platform serving 10,000+ users. Implemented microservices architecture, CI/CD pipelines, and mentored junior developers. Reduced load times by 60% through optimization.',
    startDate: '2022-01-01',
    current: true,
    technologies: ['React', 'Node.js', 'MongoDB', 'AWS', 'Docker'],
    createdAt: '',
    updatedAt: '',
  },
  {
    _id: '2',
    company: 'Digital Agency Co.',
    role: 'Full-Stack Web Developer',
    description: 'Developed and maintained multiple client websites and web applications. Collaborated with design team to implement pixel-perfect UIs. Built RESTful APIs and integrated third-party services.',
    startDate: '2020-03-01',
    endDate: '2021-12-31',
    current: false,
    technologies: ['Next.js', 'Express', 'PostgreSQL', 'Tailwind'],
    createdAt: '',
    updatedAt: '',
  },
  {
    _id: '3',
    company: 'Freelance',
    role: 'Web Developer',
    description: 'Worked with various clients to deliver custom web solutions. Specialized in e-commerce platforms and portfolio websites. Managed projects from conception to deployment.',
    startDate: '2019-01-01',
    endDate: '2020-02-28',
    current: false,
    technologies: ['React', 'Node.js', 'MongoDB', 'Stripe'],
    createdAt: '',
    updatedAt: '',
  },
]

export const sampleTestimonials = [
  {
    _id: '1',
    clientName: 'Sarah Johnson',
    review: 'Working with this developer was an absolute pleasure. They delivered our e-commerce platform ahead of schedule and exceeded all expectations. The attention to detail and code quality was exceptional.',
    company: 'TechStart Inc.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face',
    rating: 5,
    createdAt: '',
    updatedAt: '',
  },
  {
    _id: '2',
    clientName: 'Michael Chen',
    review: 'Incredible work on our SaaS application. The developer understood our vision perfectly and translated it into a beautiful, functional product. Highly recommended for any complex project.',
    company: 'CloudFlow Solutions',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    rating: 5,
    createdAt: '',
    updatedAt: '',
  },
  {
    _id: '3',
    clientName: 'Emily Davis',
    review: 'The best developer I have worked with in my 10 years of running digital projects. Professional, skilled, and always delivers on time. Our mobile app has received amazing feedback from users.',
    company: 'AppVenture Labs',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    rating: 5,
    createdAt: '',
    updatedAt: '',
  },
  {
    _id: '4',
    clientName: 'David Wilson',
    review: 'Transformed our outdated website into a modern, responsive platform that our customers love. The SEO improvements alone have increased our organic traffic by 200%.',
    company: 'Growth Marketing Co.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    rating: 5,
    createdAt: '',
    updatedAt: '',
  },
]

export const sampleStats = {
  totalProjects: 50,
  happyClients: 35,
  yearsExperience: 5,
  linesOfCode: 500000,
}
